### ISSUE TITLE
Failed to work with Laravel 5.3

### ISSUE THREAD

**Issue by louxusian** [killtw/laravel-api#1]
Hi, I have upgraded Laravel project from version 5.2 to 5.3 and it requires symfony/http-kernel version 3.1.\*.

Since killtw/laravel-api 1.0.7 requires symfony/http-kernel version "2.8.\*|3.0.\*", I can only use laravel-api 1.0.0 but it has bugs (which is fixed in 1.0.4). Is it possible to support symfony/http-kernel 3.1.\* ? 

Thanks!

**Comment by killtw** [comment]
#2 merged
